### ISSUE TITLE
is it possible to change some values?

### ISSUE THREAD

**Issue by Jsennin1** [WZG-Mods/wzg-icarus-balance-overhaul#1]
I tried to open pak file with notepad and changed some mats for the fabricator (made required electronics = 1 ) .however when I saved it, it didn't work and even though I undo the change, mod completely break (after deleting pak and re-copying it fixed). So, how can I change values? thank you

Btw sorry if this question is stupid, I don't have any experience with modding and unreal engine :)

**Comment by MunchyG** [comment]
https://discord.gg/Fp5zd23r

unpack the .pak using the DRGPaker2  which you can get from the google drive link in the tools channel in this discord
it also has a repacker to build the mod again, but requires some modification

**Comment by Jsennin1** [comment]
it works thank you
