### ISSUE TITLE
Inarus 'lua' envirosuit not auto-consuming oxygen from shengong tank

### ISSUE THREAD

**Issue by Damodredd** [WZG-Mods/wzg-icarus-balance-overhaul#10]
Inarus 'lua' envirosuit is not auto-consuming oxygen from shengong tank purchased in the workshop after installing this mod on a dedicated server.

Easy workaround by manually right clicking for consume but it kind of goes against the theme.

**Comment by WZG-Mods** [comment]
This problem can occur when, due to a combination of modules and perks, oxygen consumption is less than 0%
