### ISSUE TITLE
Sprain

### ISSUE THREAD

**Issue by bigfr0g** [WZG-Mods/wzg-icarus-balance-overhaul#2]
hi there

sometimes we get a sprain with the wzg mods but with no timer

the only solution is to logout and login again, then its gone

maybe when you have time to check this out it would make every greater then it already is ;)

**Comment by bigfr0g** [comment]
problem still exists...

**Comment by Stonedhead** [comment]
Yes, I have the same problem

In my Outpost (Iceland) it seems not to be working at all (normal timer until sprain/broken leg is gone)

As well there seems to be a "problem" with the Vapor Condenser for the Geysir. I have two Geysir's in the Iceland-Outpost and both of them stop at 92% during the first wave..
