### ISSUE TITLE
No Exotics on Spirit Walk Mission

### ISSUE THREAD

**Issue by Sturmann77** [WZG-Mods/wzg-icarus-balance-overhaul#5]
Hi!

If i mine Exotics in Spirit Walk Mission, and I recall the dropship with the dropship grenade, I am not able to drop the exotics into the dropship inventory.

Even if I put the exotics in to the taskbar, no exotics will be collected after mission end.

**Comment by KiichigoUsagi** [comment]
keep in mind that the way to deliver exotics had changed in the base game in week 53.
you now have to use the orbital exchange interface which you can craft on the planet in order to deliver exotics
