### ISSUE TITLE
Silica Ore to Glass in concrete furnace

### ISSUE THREAD

**Issue by vdubedout** [WZG-Mods/wzg-icarus-balance-overhaul#8]
![image](https://user-images.githubusercontent.com/657721/217981874-c4cf61bc-e036-4b62-8900-93dedc4e9475.png)

1 silica ore gives 10 glass. It's a bit overkill like this.
I thought it was 15 silica gives 1 glass.

**Comment by Kyoss79** [comment]
In the base game ... I think 2 silica gave 1 glass.
